# Generated by Django 3.2 on 2022-10-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_email', models.EmailField(max_length=70, unique=True)),
                ('news_name', models.CharField(max_length=70)),
                ('news_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
