# Generated by Django 3.2 on 2022-11-08 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='duration',
        ),
        migrations.AddField(
            model_name='coupon',
            name='date_end',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
