# Generated by Django 3.2 on 2022-11-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20221108_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
