# Generated by Django 3.2 on 2022-10-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Payment Approved', 'Payment Approved'), ('Order sent to separation', 'Order sent to separation'), ('Order picked', 'Order picked'), ('Order packed', 'Order packed'), ('Order shipped', 'Order shipped'), ('Order delivered', 'Order delivered')], default='Payment Approved', max_length=25),
        ),
    ]
