# Generated by Django 3.2 on 2022-11-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20221031_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer_active',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_available',
            field=models.IntegerField(default=100, max_length=5),
        ),
    ]
