# Generated by Django 3.2 on 2022-11-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20221103_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_available',
            field=models.IntegerField(default=100),
        ),
    ]
